apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-project-settings
  namespace: argo-cd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      include: '{*project.yaml, *cluster.yaml}'
    path: is01
    repoURL: git@github.com:ilyLovesCode/argo-cd.git
    targetRevision: HEAD