apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-project-1
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ilyLovesCode/argo-cd.git
    path: charts/projects/project1/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
