apiVersion: v1
kind: Secret
metadata:
  name: test-project
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ilyLovesCode/argo-cd.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACADKi85cAJhePOAC5fXumeI5eOCkHizvs6sHnjJmpbNsQAAAKA8Nl5TPDZe
    UwAAAAtzc2gtZWQyNTUxOQAAACADKi85cAJhePOAC5fXumeI5eOCkHizvs6sHnjJmpbNsQ
    AAAEA1j/dLCw5Wy6y1fQ3lawdT1q792xRBF/pg2WZXODXv2AMqLzlwAmF484ALl9e6Z4jl
    44KQeLO+zqweeMmals2xAAAAHElMWUBNYWNCb29rLVByby11c2VyLTIubG9jYWwB
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true" # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"